# Generated by Django 5.1.6 on 2025-02-20 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwimMeet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meet_title', models.CharField(max_length=100)),
                ('meet_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SwimStroke',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stroke_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwimStrokeSkills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stroke_skill', models.CharField(max_length=100)),
                ('swim_stroke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='swimmermatrix.swimstroke')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competitive', 'Competitive'), ('champion', 'Champion')], max_length=20)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='swimmermatrix.swimmer')),
                ('swim_stroke_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmer_levels', to='swimmermatrix.swimstrokeskills')),
            ],
        ),
    ]
