# Generated by Django 5.1.6 on 2025-02-20 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmermatrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='swim_meet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='swimmermatrix.swimmeet'),
        ),
    ]
