# Generated by Django 5.1.6 on 2025-02-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmermatrix', '0002_skilllevel_swim_meet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swimmeet',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='swimmeet',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
