# Generated by Django 5.1.6 on 2025-02-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swimmermatrix', '0003_alter_swimmeet_options_swimmeet_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swimstrokeskills',
            old_name='stroke_skill',
            new_name='skill_name',
        ),
    ]
